import type { ModelConfig } from '../types';

export const BYTEDANCE_VIDEO_CONFIG: Record<string, ModelConfig> = {
  'OmniHuman v1.5': {
    quality: 'high',
    supports_text_to_video: true,
    supports_image_to_video: true,
    supports_turbo_mode: true,
    supports_audio: true,
    resolutions: ['720p', '1080p'],
    default_resolution: '720p',
    max_audio_files: 2,
    audio_formats: ['audio/wav', 'audio/mpeg'],
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
    audio_duration_limit_720p: 60,
    audio_duration_limit_1080p: 30,
  },

  'Seedance V1.5 Pro': {
    quality: 'premium',
    supports_text_to_video: true,
    supports_image_to_video: true,
    supports_first_last_frames: true,
    supports_camera_fixed: true,
    supports_sound_generation: true,
    aspect_ratios: ['1:1', '4:3', '3:4', '9:16', '16:9', '21:9'],
    duration: [4, 5, 6, 7, 8, 9, 10, 11, 12],
    resolutions: ['480p', '720p', '1080p'],
    default_duration: '4s',
    default_aspect_ratio: '1:1',
    default_resolution: '480p',
    max_image_size_mb: 30,
    max_audio_size_mb: 50,
    max_audio_files: 1,
    audio_formats: ['audio/mpeg', 'audio/wav', 'audio/mp3'],
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
  },

  'Seedance 2.0': {
    quality: 'cinematic',
    supports_text_to_video: true,
    supports_image_to_video: true,
    supports_first_last_frames: true,
    supports_sound_generation: true,
    supports_reference_to_video: true,
    supports_seed: true,
    supports_audio: true,
    supports_reference_preview_in_prompt: true,
    aspect_ratios: ['auto', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    duration: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    resolutions: ['480p', '720p'],
    default_duration: '4s',
    default_aspect_ratio: 'auto',
    default_resolution: '720p',
    max_image_size_mb: 30,
    max_video_size_mb: 50,
    max_audio_size_mb: 15,
    max_multi_images: 9,
    max_reference_videos: 3,
    max_reference_audio: 3,
    supported_mime_types: ['image/png', 'image/jpeg', 'image/webp'],
    video_formats: ['video/mp4', 'video/quicktime'],
    audio_formats: ['audio/mpeg', 'audio/wav'],
  },

  'Seedance 2.0 Fast': {
    quality: 'cinematic',
    variant: 'fast',
    supports_text_to_video: true,
    supports_image_to_video: true,
    supports_first_last_frames: true,
    supports_sound_generation: true,
    supports_reference_to_video: true,
    supports_seed: true,
    supports_audio: true,
    supports_reference_preview_in_prompt: true,
    aspect_ratios: ['auto', '21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    duration: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    resolutions: ['480p', '720p'],
    default_duration: '4s',
    default_aspect_ratio: 'auto',
    default_resolution: '720p',
    max_image_size_mb: 30,
    max_video_size_mb: 50,
    max_audio_size_mb: 15,
    max_multi_images: 9,
    max_reference_videos: 3,
    max_reference_audio: 3,
    supported_mime_types: ['image/png', 'image/jpeg', 'image/webp'],
    video_formats: ['video/mp4', 'video/quicktime'],
    audio_formats: ['audio/mpeg', 'audio/wav'],
  },
};

export const BYTEDANCE_FALLBACK_CONFIG: ModelConfig = BYTEDANCE_VIDEO_CONFIG['Seedance V1.5 Pro'];
