import type { ModelConfig } from '../types';

export const KLING_VIDEO_CONFIG: Record<string, ModelConfig> = {
  'kling-v3': {
    quality: 'high',
    framerate: '30fps',
    aspect_ratios: ['16:9', '9:16', '1:1'],
    duration: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    shot_type: ['customize'],
    supports_text_to_video: true,
    supports_image_to_video: true,
    supports_first_last_frames: true,
    supports_multi_prompt: true,
    supports_elements: true,
    supports_voice_ids: true,
    supports_native_audio: true,
    supports_sound: true,
    supports_negative_prompt: true,
    supports_cfg_scale: true,
    cfg_scale_range: [0, 1],
    default_duration: '3s',
    default_sound: 'on',
    default_aspect_ratio: '16:9',
    default_cfg_scale: 0.5,
    max_voice_ids: 2,
    max_prompt_length: 2500,
    max_negative_prompt_length: 2500,
    max_image_size_mb: 10,
    max_multi_images: 7,
    max_shots: 5,
    max_elements: 3,
    max_element_images: 3,
    min_image_dimensions: '300x300',
    image_aspect_ratio_range: '1:2.5 to 2.5:1',
    output_format: 'mp4',
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
  },

  'kling-v3-pro': {
    quality: 'premium',
    framerate: '30fps',
    aspect_ratios: ['16:9', '9:16', '1:1'],
    duration: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    shot_type: ['customize'],
    supports_text_to_video: true,
    supports_image_to_video: true,
    supports_first_last_frames: true,
    supports_multi_prompt: true,
    supports_elements: true,
    supports_voice_ids: true,
    supports_native_audio: true,
    supports_sound: true,
    supports_negative_prompt: true,
    supports_cfg_scale: true,
    cfg_scale_range: [0, 1],
    default_duration: '3s',
    default_sound: 'on',
    default_aspect_ratio: '16:9',
    default_cfg_scale: 0.5,
    max_voice_ids: 2,
    max_prompt_length: 2500,
    max_negative_prompt_length: 2500,
    max_image_size_mb: 10,
    max_multi_images: 7,
    max_shots: 5,
    max_elements: 3,
    max_element_images: 3,
    min_image_dimensions: '300x300',
    image_aspect_ratio_range: '1:2.5 to 2.5:1',
    output_format: 'mp4',
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
  },

  'kling-o3': {
    quality: 'high',
    framerate: '30fps',
    aspect_ratios: ['16:9', '9:16', '1:1'],
    duration: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    shot_type: ['customize'],
    supports_text_to_video: true,
    supports_multi_image_to_video: true,
    supports_reference_to_video: true,
    supports_multi_prompt: true,
    supports_elements: true,
    supports_native_audio: true,
    supports_sound: true,
    supports_negative_prompt: false,
    default_duration: '3s',
    default_sound: 'on',
    default_aspect_ratio: '16:9',
    max_prompt_length: 2500,
    max_image_size_mb: 10,
    max_multi_images: 7,
    max_shots: 5,
    max_elements: 3,
    max_element_images: 3,
    min_image_dimensions: '300x300',
    image_aspect_ratio_range: '1:2.5 to 2.5:1',
    output_format: 'mp4',
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
  },

  'kling-o3-pro': {
    quality: 'premium',
    framerate: '30fps',
    aspect_ratios: ['16:9', '9:16', '1:1'],
    duration: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    shot_type: ['customize'],
    supports_text_to_video: true,
    supports_multi_image_to_video: true,
    supports_reference_to_video: false,
    supports_elements: true,
    supports_multi_prompt: true,
    supports_native_audio: true,
    supports_sound: true,
    supports_negative_prompt: false,
    default_duration: '3s',
    default_sound: 'on',
    default_aspect_ratio: '16:9',
    max_prompt_length: 2500,
    max_shots: 5,
    max_elements: 3,
    max_element_images: 3,
    max_multi_images: 7,
    output_format: 'mp4',
  },

  'kling-v2-1': {
    quality: 'premium',
    framerate: '30fps',
    modes: ['std', 'pro'],
    aspect_ratios: ['16:9', '9:16', '1:1'],
    duration: [5, 10],
    supports_text_to_video: true,
    supports_image_to_video: true,
    supports_first_last_frames: true,
    supports_negative_prompt: true,
    supports_cfg_scale: false,
    supports_sound: false,
    default_duration: '5s',
    default_aspect_ratio: '16:9',
    default_mode: 'pro',
    max_image_size_mb: 10,
    max_prompt_length: 2500,
    max_negative_prompt_length: 2500,
    min_image_dimensions: '300x300',
    image_aspect_ratio_range: '1:2.5 to 2.5:1',
    output_format: 'mp4',
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
  },

  'kling-v2': {
    quality: 'premium',
    framerate: '30fps',
    modes: ['std', 'pro'],
    aspect_ratios: ['16:9', '9:16', '1:1'],
    duration: [5, 10],
    supports_text_to_video: true,
    supports_image_to_video: true,
    supports_first_last_frames: true,
    supports_negative_prompt: true,
    supports_cfg_scale: false,
    supports_sound: false,
    default_duration: '5s',
    default_aspect_ratio: '16:9',
    default_mode: 'pro',
    max_image_size_mb: 10,
    max_prompt_length: 2500,
    max_negative_prompt_length: 2500,
    min_image_dimensions: '300x300',
    image_aspect_ratio_range: '1:2.5 to 2.5:1',
    output_format: 'mp4',
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
  },

  'kling-v1-5': {
    quality: 'high',
    framerate: '30fps',
    modes: ['std', 'pro'],
    aspect_ratios: ['16:9', '9:16', '1:1'],
    duration: [5, 10],
    supports_text_to_video: true,
    supports_image_to_video: true,
    supports_first_last_frames: false,
    supports_negative_prompt: true,
    supports_cfg_scale: false,
    supports_sound: false,
    cfg_scale_range: [0, 1],
    default_duration: '5s',
    default_aspect_ratio: '16:9',
    default_mode: 'pro',
    default_cfg_scale: 0.5,
    max_image_size_mb: 10,
    max_prompt_length: 2500,
    max_negative_prompt_length: 2500,
    min_image_dimensions: '300x300',
    image_aspect_ratio_range: '1:2.5 to 2.5:1',
    output_format: 'mp4',
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
  },

  'kling-v1': {
    quality: 'high',
    framerate: '30fps',
    modes: ['std', 'pro'],
    aspect_ratios: ['16:9', '9:16', '1:1'],
    duration: [5, 10],
    supports_text_to_video: true,
    supports_image_to_video: true,
    supports_first_last_frames: false,
    supports_negative_prompt: true,
    supports_cfg_scale: false,
    supports_sound: false,
    cfg_scale_range: [0, 1],
    default_duration: '5s',
    default_aspect_ratio: '16:9',
    default_mode: 'pro',
    default_cfg_scale: 0.5,
    max_image_size_mb: 10,
    max_prompt_length: 2500,
    max_negative_prompt_length: 2500,
    min_image_dimensions: '300x300',
    image_aspect_ratio_range: '1:2.5 to 2.5:1',
    output_format: 'mp4',
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
  },

  'kling-o3-pro-v2v-edit': {
    quality: 'premium',
    framerate: '30fps',
    shot_type: ['customize'],
    supports_video_to_video: true,
    supports_elements: true,
    supports_keep_original_sound: true,
    supports_multi_image_to_video: true,
    max_prompt_length: 2500,
    max_multi_images: 4,
    max_elements: 2,
    max_element_images: 3,
    max_video_size_mb: 200,
    max_image_size_mb: 10,
    output_format: 'mp4',
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
    video_formats: ['video/mp4', 'video/quicktime'],
  },

  'kling-v3-pro-motion-control': {
    quality: 'premium',
    character_orientations: ['image', 'video'],
    default_character_orientation: 'video',
    supports_motion_control: true,
    supports_character_animation: true,
    supports_prompt_guidance: true,
    supports_keep_original_sound: true,
    supports_elements: true,
    max_elements: 1,
    max_element_images: 1,
    max_image_size_mb: 10,
    max_video_size_mb: 100,
    max_prompt_length: 2500,
    output_format: 'mp4',
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
    video_formats: ['video/mp4', 'video/quicktime'],
  },
};

export const KLING_FALLBACK_CONFIG: ModelConfig = KLING_VIDEO_CONFIG['kling-v3'];
