import type { ModelConfig } from '../types';

export const WAN_VIDEO_CONFIG: Record<string, ModelConfig> = {
  'wan-2-6-t2v': {
    quality: 'high',
    supports_text_to_video: true,
    supports_negative_prompt: true,
    supports_prompt_expansion: true,
    supports_audio: true,
    duration: [5, 10, 15],
    resolutions: ['1280*720', '1920*1080'],
    shot_type: ['single', 'multi'],
    default_duration: '5s',
    default_resolution: '1280*720',
    max_prompt_length: 800,
    max_negative_prompt_length: 500,
    max_audio_size_mb: 15,
    audio_formats: ['audio/wav', 'audio/mpeg'],
    min_max_audio_duration: [3, 30],
  },

  'wan-2-6-i2v': {
    quality: 'high',
    supports_text_to_video: true,
    supports_image_to_video: true,
    supports_negative_prompt: true,
    supports_prompt_expansion: true,
    supports_audio: true,
    duration: [5, 10, 15],
    resolutions: ['1280*720', '1920*1080'],
    shot_type: ['single', 'multi'],
    default_duration: '5s',
    default_resolution: '1280*720',
    max_prompt_length: 800,
    max_negative_prompt_length: 500,
    max_image_size_mb: 25,
    audio_formats: ['audio/wav', 'audio/mpeg'],
    min_max_audio_duration: [3, 30],
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
  },

  'wan-v2-2-animate-replace': {
    quality: 'high',
    resolutions: ['480p', '720p'],
    default_resolution: '480p',
    supports_motion_control: true,
    video_qualities: ['low', 'medium', 'high', 'maximum'],
    audio_formats: ['audio/mpeg', 'audio/wav', 'audio/mp3'],
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
  },

  'wan-v2-2-animate-move': {
    quality: 'high',
    resolutions: ['480p', '720p'],
    default_resolution: '480p',
    supports_motion_control: true,
    video_qualities: ['low', 'medium', 'high', 'maximum'],
    audio_formats: ['audio/mpeg', 'audio/wav', 'audio/mp3'],
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg'],
  },

  'wan-2-7': {
    quality: 'high',
    supports_text_to_video: true,
    supports_image_to_video: true,
    supports_video_to_video: true,
    supports_first_last_frames: true,
    supports_negative_prompt: true,
    supports_prompt_expansion: true,
    supports_audio: true,
    supports_seed: true,
    duration: [5, 10, 15],
    resolutions: ['720p', '1080p'],
    aspect_ratios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    default_duration: '5s',
    default_resolution: '720p',
    default_aspect_ratio: '16:9',
    max_prompt_length: 5000,
    max_negative_prompt_length: 500,
    max_image_size_mb: 20,
    max_audio_size_mb: 15,
    audio_formats: ['audio/wav', 'audio/mpeg'],
    min_max_audio_duration: [2, 30],
    supported_mime_types: ['image/png', 'image/jpeg', 'image/jpg', 'image/bmp', 'image/webp'],
    output_format: 'mp4',
  },
};

export const WAN_FALLBACK_CONFIG: ModelConfig = WAN_VIDEO_CONFIG['wan-2-6-t2v'];
